#####################################
#                  ^ x
#                  |    
#        frame_dy  |  frame_dy
#      2<--------->|<--------->0
#      ^           |
#      |           |
#      | frame_dx  |
#      v           |
# <----------------|---------------->
# y    ^           |
#      |           |
#      | frame_dx  |
#      |           |
#      v           |
#      1           |           3
#                  v

/**:
  ros__parameters:
    # dynamics
    mav_name: "quadrotor"
    platform_type: "eagle"
    gravity: 9.80665
    mass: 1.0
    # mass: 1.176   # race7, race8
    frame_dx: 0.078
    frame_dy: 0.0985
    motor_time_constant: 0.05
    min_rpm: 1080.0
    max_rpm: 24000.0
    drag_coefficient: 0.0
    kf: 2.47e-08
    km: 2.68e-10
    ixx: 0.00305587
    iyy: 0.00159695
    izz: 0.00159687

    # nmpc_control_params
    nmpc:
      Q:   [210., 210., 210., 250., 1., 1., 1., 5., 5., 5., 5., 1., 1., 1.]
      Q_e: [210., 210., 210., 250., 1., 1., 1., 5., 5., 5., 5., 1., 1., 1.]
      R:   [0.7, 0.1, 0.1, 0.1]
      nx: 14
      nu: 4
      lbu: [0.2, -0.45, -0.45, -0.45]
      ubu: [42.0, 0.45, 0.45, 0.45]
      horizon_steps: 21
      horizon_time: 1.5
      ts: 0.03

    # px4 interface
    lin_cof_a: 0.00005
    lin_int_b: -0.35
    so3_cmd_timeout: 0.25
    trpy_cmd_timeout: 0.25

    # so3_control_params
    # Reducing angular derivative
    gains:
      pos:
        x: 7.1 # 1.8
        y: 7.1 # 1.8
        z: 11.9 # 3.0
          #z: 9.0 # 3.0
      vel:
        x: 2.4 # 0.6
        y: 2.4 # 0.6
        z: 6.7 # 1.7
          #z: 5.0 # 1.7
      rot:
        x: 1.5
        y: 1.5
        z: 1.0
      ang:
        x: 0.13
        y: 0.13
        z: 0.1
      ki:
        x: 0.00 # 0.00
        y: 0.004 # 0.001
        z: 0.03 # 0.008
    
    # tracker_params
    qp_tracker:
      v_max: 2.0
      a_max: 4.0
      degree_optimize: 4
      x_max: 2.0
      x_min: -2.0
      y_max: 1.5
      y_min: -1.5
      z_max: 2.0
      z_min: 0.2
    
    line_tracker_distance:
      default_v_des: 0.3
      default_a_des: 0.2
      epsilon: 0.1
    
    line_tracker_min_jerk:
      default_v_des: 0.3
      default_a_des: 0.2
      default_yaw_v_des: 0.5
      default_yaw_a_des: 0.2
    
    trajectory_tracker:
      max_vel_des: 0.3
      max_acc_des: 0.2
    
    # trackers
    trackers:
      - std_trackers/LineTrackerMinJerkAction
      - std_trackers/LineTrackerDistanceAction
      - std_trackers/LissajousTrackerAction
      - std_trackers/VelocityTrackerAction
      - std_trackers/NullTracker
      - std_trackers/CircleTrackerAction
      - std_trackers/TrajectoryTracker
      - std_trackers/SmoothVelTrackerAction
      - std_trackers/QPTrackerAction
    
    # mav_manager_params
    need_imu: false
    need_output_data: true
    use_attitude_safety_catch: false
    max_attitude_angle: 0.43
    takeoff_height: 0.5
